### PR TITLE
Add warning for package developers to README

### PR DESCRIPTION
**Pull request by nalimilan**

### CODE REVIEW

**Comment by nalimilan** [comment]
Do you feel like developing?

**Comment by matbesancon** [comment]
Yes, I'll try to add to the PR later in the evening

**Comment by matbesancon** [comment]
feel free to modify the modification :)

**Comment by nalimilan** [comment]
I can't see it... :-/

**Comment by ararslan** [comment]
Nor can I. @matbesancon, perhaps you forgot to `git push`?

**Pull request merged**
