### PR TITLE
Switch to Project.toml

### PR DESCRIPTION
**Pull request by nalimilan**

### CODE REVIEW

**Comment by ararslan** [comment]
This will also need a version and compatibility entries for each dependency.

**Comment by nalimilan** [comment]
Given that this is just a meta-package and that we won't tag new versions very frequently, I'd say we'd better not add any bounds. We just want the most recent combination dependencies that are compatible with each other.

**Comment by ararslan** [comment]
I'd agree in general, but I think automatic merging in the General registry requires compatibility bounds for all dependencies.

**Comment by KristofferC** [comment]
Things can be non-auto merged though.

**Comment by nalimilan** [comment]
Yes, as we don't tag releases frequently (only when adding new packages), it's not an issue if we require manual merging.

**Comment by ararslan** [comment]
Okay, sounds good.

**Pull request merged**
